name: Deploy Pages

on:
  workflow_dispatch:
  schedule:
    - cron: "*/10 * * * *"

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout deploy repo
        uses: actions/checkout@v4

      - name: Checkout source repo
        uses: actions/checkout@v4
        with:
          repository: Baebear0903/DIP-Analysis
          path: source
          # 如果原仓库是私有仓库，打开下面这行
          # token: ${{ secrets.AISTUDIO_REPO_TOKEN }}

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: source

      - name: Deploy
        uses: actions/deploy-pages@v4
